# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolov5_flame_smog.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17yolov5_flame_smog.proto\x12\x11yolov5_flame_smog\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x19\n\tVideoPath\x12\x0c\n\x04path\x18\x01 \x01(\t2\xb8\x01\n\x16Yolov5FlameSmogService\x12J\n\x14yolov5FlameSmogImage\x12\x18.yolov5_flame_smog.Image\x1a\x18.yolov5_flame_smog.Image\x12R\n\x14yolov5FlameSmogVideo\x12\x1c.yolov5_flame_smog.VideoPath\x1a\x1c.yolov5_flame_smog.VideoPathB\x15Z\x13./yolov5_flame_smogb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolov5_flame_smog_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\023./yolov5_flame_smog'
  _IMAGE._serialized_start=46
  _IMAGE._serialized_end=68
  _VIDEOPATH._serialized_start=70
  _VIDEOPATH._serialized_end=95
  _YOLOV5FLAMESMOGSERVICE._serialized_start=98
  _YOLOV5FLAMESMOGSERVICE._serialized_end=282
# @@protoc_insertion_point(module_scope)
