# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_grpc.yolov5_flame_smog_pb2 as yolov5__flame__smog__pb2


class Yolov5FlameSmogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.yolov5FlameSmogImage = channel.unary_unary(
                '/yolov5_flame_smog.Yolov5FlameSmogService/yolov5FlameSmogImage',
                request_serializer=yolov5__flame__smog__pb2.Image.SerializeToString,
                response_deserializer=yolov5__flame__smog__pb2.Image.FromString,
                )
        self.yolov5FlameSmogVideo = channel.unary_unary(
                '/yolov5_flame_smog.Yolov5FlameSmogService/yolov5FlameSmogVideo',
                request_serializer=yolov5__flame__smog__pb2.VideoPath.SerializeToString,
                response_deserializer=yolov5__flame__smog__pb2.VideoPath.FromString,
                )


class Yolov5FlameSmogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def yolov5FlameSmogImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def yolov5FlameSmogVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Yolov5FlameSmogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'yolov5FlameSmogImage': grpc.unary_unary_rpc_method_handler(
                    servicer.yolov5FlameSmogImage,
                    request_deserializer=yolov5__flame__smog__pb2.Image.FromString,
                    response_serializer=yolov5__flame__smog__pb2.Image.SerializeToString,
            ),
            'yolov5FlameSmogVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.yolov5FlameSmogVideo,
                    request_deserializer=yolov5__flame__smog__pb2.VideoPath.FromString,
                    response_serializer=yolov5__flame__smog__pb2.VideoPath.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yolov5_flame_smog.Yolov5FlameSmogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Yolov5FlameSmogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def yolov5FlameSmogImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yolov5_flame_smog.Yolov5FlameSmogService/yolov5FlameSmogImage',
            yolov5__flame__smog__pb2.Image.SerializeToString,
            yolov5__flame__smog__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def yolov5FlameSmogVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yolov5_flame_smog.Yolov5FlameSmogService/yolov5FlameSmogVideo',
            yolov5__flame__smog__pb2.VideoPath.SerializeToString,
            yolov5__flame__smog__pb2.VideoPath.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
