// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: yolov5_classify_life_jacket.proto

package yolov5_classify_life_jacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatasetPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	JsonPath string `protobuf:"bytes,2,opt,name=json_path,json=jsonPath,proto3" json:"json_path,omitempty"`
}

func (x *DatasetPath) Reset() {
	*x = DatasetPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yolov5_classify_life_jacket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatasetPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetPath) ProtoMessage() {}

func (x *DatasetPath) ProtoReflect() protoreflect.Message {
	mi := &file_yolov5_classify_life_jacket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetPath.ProtoReflect.Descriptor instead.
func (*DatasetPath) Descriptor() ([]byte, []int) {
	return file_yolov5_classify_life_jacket_proto_rawDescGZIP(), []int{0}
}

func (x *DatasetPath) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DatasetPath) GetJsonPath() string {
	if x != nil {
		return x.JsonPath
	}
	return ""
}

type ResultJson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResultJson) Reset() {
	*x = ResultJson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yolov5_classify_life_jacket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultJson) ProtoMessage() {}

func (x *ResultJson) ProtoReflect() protoreflect.Message {
	mi := &file_yolov5_classify_life_jacket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultJson.ProtoReflect.Descriptor instead.
func (*ResultJson) Descriptor() ([]byte, []int) {
	return file_yolov5_classify_life_jacket_proto_rawDescGZIP(), []int{1}
}

func (x *ResultJson) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_yolov5_classify_life_jacket_proto protoreflect.FileDescriptor

var file_yolov5_classify_life_jacket_proto_rawDesc = []byte{
	0x0a, 0x21, 0x79, 0x6f, 0x6c, 0x6f, 0x76, 0x35, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x79, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x5f, 0x6a, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x1b, 0x0a, 0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x22, 0x20, 0x0a, 0x0a,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x60,
	0x0a, 0x23, 0x54, 0x65, 0x73, 0x74, 0x59, 0x6f, 0x6c, 0x6f, 0x76, 0x35, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x79, 0x4c, 0x69, 0x66, 0x65, 0x4a, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x1c, 0x74, 0x65, 0x73, 0x74, 0x59, 0x6f, 0x6c,
	0x6f, 0x76, 0x35, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x4c, 0x69, 0x66, 0x65, 0x4a,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x1a, 0x0b, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4a, 0x73, 0x6f, 0x6e,
	0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x79, 0x6f, 0x6c, 0x6f, 0x76, 0x35, 0x5f, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x69, 0x66, 0x79, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x5f, 0x6a, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yolov5_classify_life_jacket_proto_rawDescOnce sync.Once
	file_yolov5_classify_life_jacket_proto_rawDescData = file_yolov5_classify_life_jacket_proto_rawDesc
)

func file_yolov5_classify_life_jacket_proto_rawDescGZIP() []byte {
	file_yolov5_classify_life_jacket_proto_rawDescOnce.Do(func() {
		file_yolov5_classify_life_jacket_proto_rawDescData = protoimpl.X.CompressGZIP(file_yolov5_classify_life_jacket_proto_rawDescData)
	})
	return file_yolov5_classify_life_jacket_proto_rawDescData
}

var file_yolov5_classify_life_jacket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yolov5_classify_life_jacket_proto_goTypes = []interface{}{
	(*DatasetPath)(nil), // 0: DatasetPath
	(*ResultJson)(nil),  // 1: ResultJson
}
var file_yolov5_classify_life_jacket_proto_depIdxs = []int32{
	0, // 0: TestYolov5ClassifyLifeJacketService.testYolov5ClassifyLifeJacket:input_type -> DatasetPath
	1, // 1: TestYolov5ClassifyLifeJacketService.testYolov5ClassifyLifeJacket:output_type -> ResultJson
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yolov5_classify_life_jacket_proto_init() }
func file_yolov5_classify_life_jacket_proto_init() {
	if File_yolov5_classify_life_jacket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yolov5_classify_life_jacket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatasetPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yolov5_classify_life_jacket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultJson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yolov5_classify_life_jacket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yolov5_classify_life_jacket_proto_goTypes,
		DependencyIndexes: file_yolov5_classify_life_jacket_proto_depIdxs,
		MessageInfos:      file_yolov5_classify_life_jacket_proto_msgTypes,
	}.Build()
	File_yolov5_classify_life_jacket_proto = out.File
	file_yolov5_classify_life_jacket_proto_rawDesc = nil
	file_yolov5_classify_life_jacket_proto_goTypes = nil
	file_yolov5_classify_life_jacket_proto_depIdxs = nil
}
