# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolov5_parking_violation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eyolov5_parking_violation.proto\x12\x18yolov5_parking_violation\"\x19\n\tVideoPath\x12\x0c\n\x04path\x18\x01 \x01(\t2\x83\x01\n\x1dYolov5ParkingViolationService\x12\x62\n\x16yolov5ParkingViolation\x12#.yolov5_parking_violation.VideoPath\x1a#.yolov5_parking_violation.VideoPathB\x1cZ\x1a./yolov5_parking_violationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolov5_parking_violation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032./yolov5_parking_violation'
  _VIDEOPATH._serialized_start=60
  _VIDEOPATH._serialized_end=85
  _YOLOV5PARKINGVIOLATIONSERVICE._serialized_start=88
  _YOLOV5PARKINGVIOLATIONSERVICE._serialized_end=219
# @@protoc_insertion_point(module_scope)
