# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolov5_leakage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14yolov5_leakage.proto\x12\x0eyolov5_leakage\"\x19\n\tVideoPath\x12\x0c\n\x04path\x18\x01 \x01(\t2\xa7\x01\n\x14Yolov5LeakageService\x12I\n\x11heatAreaDetection\x12\x19.yolov5_leakage.VideoPath\x1a\x19.yolov5_leakage.VideoPath\x12\x44\n\x0coilDetection\x12\x19.yolov5_leakage.VideoPath\x1a\x19.yolov5_leakage.VideoPathB\x12Z\x10./yolov5_leakageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolov5_leakage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\020./yolov5_leakage'
  _VIDEOPATH._serialized_start=40
  _VIDEOPATH._serialized_end=65
  _YOLOV5LEAKAGESERVICE._serialized_start=68
  _YOLOV5LEAKAGESERVICE._serialized_end=235
# @@protoc_insertion_point(module_scope)
