// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.0
// source: yolov5_leakage.proto

package yolov5_leakage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Yolov5LeakageServiceClient is the client API for Yolov5LeakageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Yolov5LeakageServiceClient interface {
	HeatAreaDetection(ctx context.Context, in *VideoPath, opts ...grpc.CallOption) (*VideoPath, error)
	OilDetection(ctx context.Context, in *VideoPath, opts ...grpc.CallOption) (*VideoPath, error)
}

type yolov5LeakageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYolov5LeakageServiceClient(cc grpc.ClientConnInterface) Yolov5LeakageServiceClient {
	return &yolov5LeakageServiceClient{cc}
}

func (c *yolov5LeakageServiceClient) HeatAreaDetection(ctx context.Context, in *VideoPath, opts ...grpc.CallOption) (*VideoPath, error) {
	out := new(VideoPath)
	err := c.cc.Invoke(ctx, "/yolov5_leakage.Yolov5LeakageService/heatAreaDetection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yolov5LeakageServiceClient) OilDetection(ctx context.Context, in *VideoPath, opts ...grpc.CallOption) (*VideoPath, error) {
	out := new(VideoPath)
	err := c.cc.Invoke(ctx, "/yolov5_leakage.Yolov5LeakageService/oilDetection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Yolov5LeakageServiceServer is the server API for Yolov5LeakageService service.
// All implementations must embed UnimplementedYolov5LeakageServiceServer
// for forward compatibility
type Yolov5LeakageServiceServer interface {
	HeatAreaDetection(context.Context, *VideoPath) (*VideoPath, error)
	OilDetection(context.Context, *VideoPath) (*VideoPath, error)
	mustEmbedUnimplementedYolov5LeakageServiceServer()
}

// UnimplementedYolov5LeakageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedYolov5LeakageServiceServer struct {
}

func (UnimplementedYolov5LeakageServiceServer) HeatAreaDetection(context.Context, *VideoPath) (*VideoPath, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeatAreaDetection not implemented")
}
func (UnimplementedYolov5LeakageServiceServer) OilDetection(context.Context, *VideoPath) (*VideoPath, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OilDetection not implemented")
}
func (UnimplementedYolov5LeakageServiceServer) mustEmbedUnimplementedYolov5LeakageServiceServer() {}

// UnsafeYolov5LeakageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Yolov5LeakageServiceServer will
// result in compilation errors.
type UnsafeYolov5LeakageServiceServer interface {
	mustEmbedUnimplementedYolov5LeakageServiceServer()
}

func RegisterYolov5LeakageServiceServer(s grpc.ServiceRegistrar, srv Yolov5LeakageServiceServer) {
	s.RegisterService(&Yolov5LeakageService_ServiceDesc, srv)
}

func _Yolov5LeakageService_HeatAreaDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Yolov5LeakageServiceServer).HeatAreaDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yolov5_leakage.Yolov5LeakageService/heatAreaDetection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Yolov5LeakageServiceServer).HeatAreaDetection(ctx, req.(*VideoPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Yolov5LeakageService_OilDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Yolov5LeakageServiceServer).OilDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yolov5_leakage.Yolov5LeakageService/oilDetection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Yolov5LeakageServiceServer).OilDetection(ctx, req.(*VideoPath))
	}
	return interceptor(ctx, in, info, handler)
}

// Yolov5LeakageService_ServiceDesc is the grpc.ServiceDesc for Yolov5LeakageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Yolov5LeakageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yolov5_leakage.Yolov5LeakageService",
	HandlerType: (*Yolov5LeakageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "heatAreaDetection",
			Handler:    _Yolov5LeakageService_HeatAreaDetection_Handler,
		},
		{
			MethodName: "oilDetection",
			Handler:    _Yolov5LeakageService_OilDetection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yolov5_leakage.proto",
}
