# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolov5_classify_life_jacket.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!yolov5_classify_life_jacket.proto\"3\n\x0b\x44\x61tasetPath\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x11\n\tjson_path\x18\x02 \x01(\t\"\x1a\n\nResultJson\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2`\n#TestYolov5ClassifyLifeJacketService\x12\x39\n\x1ctestYolov5ClassifyLifeJacket\x12\x0c.DatasetPath\x1a\x0b.ResultJsonB\x1fZ\x1d./yolov5_classify_life_jacketb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolov5_classify_life_jacket_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035./yolov5_classify_life_jacket'
  _DATASETPATH._serialized_start=37
  _DATASETPATH._serialized_end=88
  _RESULTJSON._serialized_start=90
  _RESULTJSON._serialized_end=116
  _TESTYOLOV5CLASSIFYLIFEJACKETSERVICE._serialized_start=118
  _TESTYOLOV5CLASSIFYLIFEJACKETSERVICE._serialized_end=214
# @@protoc_insertion_point(module_scope)
