# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_grpc.yolov5_classify_life_jacket_pb2 as yolov5__classify__life__jacket__pb2


class TestYolov5ClassifyLifeJacketServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.testYolov5ClassifyLifeJacket = channel.unary_unary(
                '/TestYolov5ClassifyLifeJacketService/testYolov5ClassifyLifeJacket',
                request_serializer=yolov5__classify__life__jacket__pb2.DatasetPath.SerializeToString,
                response_deserializer=yolov5__classify__life__jacket__pb2.ResultJson.FromString,
                )


class TestYolov5ClassifyLifeJacketServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def testYolov5ClassifyLifeJacket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestYolov5ClassifyLifeJacketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'testYolov5ClassifyLifeJacket': grpc.unary_unary_rpc_method_handler(
                    servicer.testYolov5ClassifyLifeJacket,
                    request_deserializer=yolov5__classify__life__jacket__pb2.DatasetPath.FromString,
                    response_serializer=yolov5__classify__life__jacket__pb2.ResultJson.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TestYolov5ClassifyLifeJacketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestYolov5ClassifyLifeJacketService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def testYolov5ClassifyLifeJacket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TestYolov5ClassifyLifeJacketService/testYolov5ClassifyLifeJacket',
            yolov5__classify__life__jacket__pb2.DatasetPath.SerializeToString,
            yolov5__classify__life__jacket__pb2.ResultJson.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
