# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paddle_ocr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10paddle_ocr.proto\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\x0c\"(\n\tImageText\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0c\n\x04text\x18\x02 \x01(\t23\n\x10PaddleOcrService\x12\x1f\n\tPaddleOcr\x12\x06.Image\x1a\n.ImageTextB\x0eZ\x0c./paddle_ocrb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paddle_ocr_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014./paddle_ocr'
  _IMAGE._serialized_start=20
  _IMAGE._serialized_end=42
  _IMAGETEXT._serialized_start=44
  _IMAGETEXT._serialized_end=84
  _PADDLEOCRSERVICE._serialized_start=86
  _PADDLEOCRSERVICE._serialized_end=137
# @@protoc_insertion_point(module_scope)
