# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_grpc.paddle_ocr_pb2 as paddle__ocr__pb2


class PaddleOcrServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PaddleOcr = channel.unary_unary(
                '/paddle_ocr.PaddleOcrService/PaddleOcr',
                request_serializer=paddle__ocr__pb2.Image.SerializeToString,
                response_deserializer=paddle__ocr__pb2.ImageText.FromString,
                )


class PaddleOcrServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PaddleOcr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaddleOcrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PaddleOcr': grpc.unary_unary_rpc_method_handler(
                    servicer.PaddleOcr,
                    request_deserializer=paddle__ocr__pb2.Image.FromString,
                    response_serializer=paddle__ocr__pb2.ImageText.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paddle_ocr.PaddleOcrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaddleOcrService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PaddleOcr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/paddle_ocr.PaddleOcrService/PaddleOcr',
            paddle__ocr__pb2.Image.SerializeToString,
            paddle__ocr__pb2.ImageText.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
